services:
  db:
    image: postgres:15.3
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
#      - POSTGRES_PASSWORD=nava_password
      - POSTGRES_DB=nava_api
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: nava-api:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./app/.env.docker

volumes:
  postgres_data: